<?php

/**
 * BaseScenario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * @property integer $simulation_lifespan
 * @property decimal $starting_level
 * @property decimal $saturation_level
 * @property integer $alpha
 * @property float $beta
 * 
 * @method string   getDescription()         Returns the current record's "description" value
 * @method integer  getSimulationLifespan()  Returns the current record's "simulation_lifespan" value
 * @method decimal  getStartingLevel()       Returns the current record's "starting_level" value
 * @method decimal  getSaturationLevel()     Returns the current record's "saturation_level" value
 * @method integer  getAlpha()               Returns the current record's "alpha" value
 * @method float    getBeta()                Returns the current record's "beta" value
 * @method Scenario setDescription()         Sets the current record's "description" value
 * @method Scenario setSimulationLifespan()  Sets the current record's "simulation_lifespan" value
 * @method Scenario setStartingLevel()       Sets the current record's "starting_level" value
 * @method Scenario setSaturationLevel()     Sets the current record's "saturation_level" value
 * @method Scenario setAlpha()               Sets the current record's "alpha" value
 * @method Scenario setBeta()                Sets the current record's "beta" value
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScenario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scenario');
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('simulation_lifespan', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('starting_level', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('saturation_level', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('alpha', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('beta', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}