<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $username
 * @property string $password
 * @property string $email
 * @property datetime $last_login
 * @property integer $operator_id
 * @property Operator $Operator
 * 
 * @method string   getName()        Returns the current record's "name" value
 * @method string   getUsername()    Returns the current record's "username" value
 * @method string   getPassword()    Returns the current record's "password" value
 * @method string   getEmail()       Returns the current record's "email" value
 * @method datetime getLastLogin()   Returns the current record's "last_login" value
 * @method integer  getOperatorId()  Returns the current record's "operator_id" value
 * @method Operator getOperator()    Returns the current record's "Operator" value
 * @method User     setName()        Sets the current record's "name" value
 * @method User     setUsername()    Sets the current record's "username" value
 * @method User     setPassword()    Sets the current record's "password" value
 * @method User     setEmail()       Sets the current record's "email" value
 * @method User     setLastLogin()   Sets the current record's "last_login" value
 * @method User     setOperatorId()  Sets the current record's "operator_id" value
 * @method User     setOperator()    Sets the current record's "Operator" value
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('username', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'email' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_login', 'datetime', null, array(
             'type' => 'datetime',
             ));
        $this->hasColumn('operator_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Operator', array(
             'local' => 'operator_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}