<?php

/**
 * BaseOperator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $starting_market_size
 * @property Doctrine_Collection $User
 * 
 * @method integer             getStartingMarketSize()   Returns the current record's "starting_market_size" value
 * @method Doctrine_Collection getUser()                 Returns the current record's "User" collection
 * @method Operator            setStartingMarketSize()   Sets the current record's "starting_market_size" value
 * @method Operator            setUser()                 Sets the current record's "User" collection
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOperator extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('operator');
        $this->hasColumn('starting_market_size', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'id',
             'foreign' => 'operator_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}