<?php

/**
 * BaseTariff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tick
 * @property integer $operator_id
 * @property Operator $Operator
 * 
 * @method integer  getTick()        Returns the current record's "tick" value
 * @method integer  getOperatorId()  Returns the current record's "operator_id" value
 * @method Operator getOperator()    Returns the current record's "Operator" value
 * @method Tariff   setTick()        Sets the current record's "tick" value
 * @method Tariff   setOperatorId()  Sets the current record's "operator_id" value
 * @method Tariff   setOperator()    Sets the current record's "Operator" value
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTariff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tariff');
        $this->hasColumn('tick', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('operator_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Operator', array(
             'local' => 'operator_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}