<?php

/**
 * BaseTechnology
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $first_tick_available
 * @property decimal $decline_A
 * @property decimal $decline_B
 * @property integer $operator_id
 * @property integer $scenario_id
 * @property Operator $Operator
 * @property Scenario $Scenario
 * @property Architecture $Architecture
 * @property Doctrine_Collection $Services
 * 
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getDescription()          Returns the current record's "description" value
 * @method integer             getFirstTickAvailable()   Returns the current record's "first_tick_available" value
 * @method decimal             getDeclineA()             Returns the current record's "decline_A" value
 * @method decimal             getDeclineB()             Returns the current record's "decline_B" value
 * @method integer             getOperatorId()           Returns the current record's "operator_id" value
 * @method integer             getScenarioId()           Returns the current record's "scenario_id" value
 * @method Operator            getOperator()             Returns the current record's "Operator" value
 * @method Scenario            getScenario()             Returns the current record's "Scenario" value
 * @method Architecture        getArchitecture()         Returns the current record's "Architecture" value
 * @method Doctrine_Collection getServices()             Returns the current record's "Services" collection
 * @method Technology          setName()                 Sets the current record's "name" value
 * @method Technology          setDescription()          Sets the current record's "description" value
 * @method Technology          setFirstTickAvailable()   Sets the current record's "first_tick_available" value
 * @method Technology          setDeclineA()             Sets the current record's "decline_A" value
 * @method Technology          setDeclineB()             Sets the current record's "decline_B" value
 * @method Technology          setOperatorId()           Sets the current record's "operator_id" value
 * @method Technology          setScenarioId()           Sets the current record's "scenario_id" value
 * @method Technology          setOperator()             Sets the current record's "Operator" value
 * @method Technology          setScenario()             Sets the current record's "Scenario" value
 * @method Technology          setArchitecture()         Sets the current record's "Architecture" value
 * @method Technology          setServices()             Sets the current record's "Services" collection
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTechnology extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('technology');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('first_tick_available', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('decline_A', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             ));
        $this->hasColumn('decline_B', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             ));
        $this->hasColumn('operator_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('scenario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Operator', array(
             'local' => 'operator_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Scenario', array(
             'local' => 'scenario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Architecture', array(
             'local' => 'id',
             'foreign' => 'technology_id'));

        $this->hasMany('Service as Services', array(
             'local' => 'id',
             'foreign' => 'technology_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}