<?php

/**
 * BaseDecisionPoint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $setup_fee
 * @property decimal $cost_per_user
 * @property float $CAPEX_percentage
 * @property integer $tick_to_apply
 * @property integer $operator_id
 * @property integer $scenario_id
 * @property Operator $Operator
 * @property Scenario $Scenario
 * 
 * @method decimal       getSetupFee()         Returns the current record's "setup_fee" value
 * @method decimal       getCostPerUser()      Returns the current record's "cost_per_user" value
 * @method float         getCAPEXPercentage()  Returns the current record's "CAPEX_percentage" value
 * @method integer       getTickToApply()      Returns the current record's "tick_to_apply" value
 * @method integer       getOperatorId()       Returns the current record's "operator_id" value
 * @method integer       getScenarioId()       Returns the current record's "scenario_id" value
 * @method Operator      getOperator()         Returns the current record's "Operator" value
 * @method Scenario      getScenario()         Returns the current record's "Scenario" value
 * @method DecisionPoint setSetupFee()         Sets the current record's "setup_fee" value
 * @method DecisionPoint setCostPerUser()      Sets the current record's "cost_per_user" value
 * @method DecisionPoint setCAPEXPercentage()  Sets the current record's "CAPEX_percentage" value
 * @method DecisionPoint setTickToApply()      Sets the current record's "tick_to_apply" value
 * @method DecisionPoint setOperatorId()       Sets the current record's "operator_id" value
 * @method DecisionPoint setScenarioId()       Sets the current record's "scenario_id" value
 * @method DecisionPoint setOperator()         Sets the current record's "Operator" value
 * @method DecisionPoint setScenario()         Sets the current record's "Scenario" value
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDecisionPoint extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('decision_point');
        $this->hasColumn('setup_fee', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('cost_per_user', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('CAPEX_percentage', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('tick_to_apply', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('operator_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('scenario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Operator', array(
             'local' => 'operator_id',
             'foreign' => 'id'));

        $this->hasOne('Scenario', array(
             'local' => 'scenario_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}