<?php

/**
 * BaseAcquiredEquipment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $quantity
 * @property decimal $price
 * @property integer $available_until
 * @property boolean $is_obsolete
 * @property integer $equipment_id
 * @property integer $tick_id
 * @property Tick $Tick
 * @property Equipment $Equipment
 * 
 * @method integer           getQuantity()        Returns the current record's "quantity" value
 * @method decimal           getPrice()           Returns the current record's "price" value
 * @method integer           getAvailableUntil()  Returns the current record's "available_until" value
 * @method boolean           getIsObsolete()      Returns the current record's "is_obsolete" value
 * @method integer           getEquipmentId()     Returns the current record's "equipment_id" value
 * @method integer           getTickId()          Returns the current record's "tick_id" value
 * @method Tick              getTick()            Returns the current record's "Tick" value
 * @method Equipment         getEquipment()       Returns the current record's "Equipment" value
 * @method AcquiredEquipment setQuantity()        Sets the current record's "quantity" value
 * @method AcquiredEquipment setPrice()           Sets the current record's "price" value
 * @method AcquiredEquipment setAvailableUntil()  Sets the current record's "available_until" value
 * @method AcquiredEquipment setIsObsolete()      Sets the current record's "is_obsolete" value
 * @method AcquiredEquipment setEquipmentId()     Sets the current record's "equipment_id" value
 * @method AcquiredEquipment setTickId()          Sets the current record's "tick_id" value
 * @method AcquiredEquipment setTick()            Sets the current record's "Tick" value
 * @method AcquiredEquipment setEquipment()       Sets the current record's "Equipment" value
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcquiredEquipment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('acquired_equipment');
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('price', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('available_until', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_obsolete', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('equipment_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tick_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tick', array(
             'local' => 'tick_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Equipment', array(
             'local' => 'equipment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}