<?php

/**
 * BaseScenarioTechnology
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $scenario_id
 * @property integer $technology_id
 * @property Scenario $Scenario
 * @property Technology $Technology
 * 
 * @method integer            getScenarioId()    Returns the current record's "scenario_id" value
 * @method integer            getTechnologyId()  Returns the current record's "technology_id" value
 * @method Scenario           getScenario()      Returns the current record's "Scenario" value
 * @method Technology         getTechnology()    Returns the current record's "Technology" value
 * @method ScenarioTechnology setScenarioId()    Sets the current record's "scenario_id" value
 * @method ScenarioTechnology setTechnologyId()  Sets the current record's "technology_id" value
 * @method ScenarioTechnology setScenario()      Sets the current record's "Scenario" value
 * @method ScenarioTechnology setTechnology()    Sets the current record's "Technology" value
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScenarioTechnology extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scenario_technology');
        $this->hasColumn('scenario_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('technology_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Scenario', array(
             'local' => 'scenario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Technology', array(
             'local' => 'technology_id',
             'foreign' => 'id'));
    }
}