<?php

/**
 * BaseLibEquip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property decimal $starting_price
 * @property integer $number_of_ports
 * @property integer $network_level
 * @property integer $life_expectation
 * @property enum $equipment_type
 * @property enum $nature_or_purpose
 * @property enum $tecnology_age
 * @property enum $setup_speed
 * @property integer $arch_id
 * @property LibArch $Architecture
 * 
 * @method string   getName()              Returns the current record's "name" value
 * @method decimal  getStartingPrice()     Returns the current record's "starting_price" value
 * @method integer  getNumberOfPorts()     Returns the current record's "number_of_ports" value
 * @method integer  getNetworkLevel()      Returns the current record's "network_level" value
 * @method integer  getLifeExpectation()   Returns the current record's "life_expectation" value
 * @method enum     getEquipmentType()     Returns the current record's "equipment_type" value
 * @method enum     getNatureOrPurpose()   Returns the current record's "nature_or_purpose" value
 * @method enum     getTecnologyAge()      Returns the current record's "tecnology_age" value
 * @method enum     getSetupSpeed()        Returns the current record's "setup_speed" value
 * @method integer  getArchId()            Returns the current record's "arch_id" value
 * @method LibArch  getArchitecture()      Returns the current record's "Architecture" value
 * @method LibEquip setName()              Sets the current record's "name" value
 * @method LibEquip setStartingPrice()     Sets the current record's "starting_price" value
 * @method LibEquip setNumberOfPorts()     Sets the current record's "number_of_ports" value
 * @method LibEquip setNetworkLevel()      Sets the current record's "network_level" value
 * @method LibEquip setLifeExpectation()   Sets the current record's "life_expectation" value
 * @method LibEquip setEquipmentType()     Sets the current record's "equipment_type" value
 * @method LibEquip setNatureOrPurpose()   Sets the current record's "nature_or_purpose" value
 * @method LibEquip setTecnologyAge()      Sets the current record's "tecnology_age" value
 * @method LibEquip setSetupSpeed()        Sets the current record's "setup_speed" value
 * @method LibEquip setArchId()            Sets the current record's "arch_id" value
 * @method LibEquip setArchitecture()      Sets the current record's "Architecture" value
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLibEquip extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lib_equip');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('starting_price', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('number_of_ports', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('network_level', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('life_expectation', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('equipment_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => NULL,
              1 => 'Wired',
              2 => 'Wireless',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('nature_or_purpose', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => NULL,
              1 => 'Building/Construction (1)',
              2 => 'Copper cables (1)',
              3 => 'Fiber cables (0.8)',
              4 => 'Electronics (0.9)',
              5 => 'Advanced Optical Components (0.7)',
              6 => 'Passive Optical Components (0.8)',
             ),
             ));
        $this->hasColumn('tecnology_age', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => NULL,
              1 => 'Old (0.5)',
              2 => 'Mature (0.1)',
              3 => 'New (0.01)',
              4 => 'Emerging (0.001)',
             ),
             ));
        $this->hasColumn('setup_speed', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => NULL,
              1 => 'Very fast (5)',
              2 => 'Fast (10)',
              3 => 'Slow (20)',
              4 => 'Very slow (40)',
             ),
             ));
        $this->hasColumn('arch_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LibArch as Architecture', array(
             'local' => 'arch_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}