<?php

/**
 * BaseOperator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $starting_market_size
 * @property integer $user_id
 * @property integer $scenario_id
 * @property User $User
 * @property Scenario $Scenario
 * @property Doctrine_Collection $DecisionPoints
 * 
 * @method integer             getStartingMarketSize()   Returns the current record's "starting_market_size" value
 * @method integer             getUserId()               Returns the current record's "user_id" value
 * @method integer             getScenarioId()           Returns the current record's "scenario_id" value
 * @method User                getUser()                 Returns the current record's "User" value
 * @method Scenario            getScenario()             Returns the current record's "Scenario" value
 * @method Doctrine_Collection getDecisionPoints()       Returns the current record's "DecisionPoints" collection
 * @method Operator            setStartingMarketSize()   Sets the current record's "starting_market_size" value
 * @method Operator            setUserId()               Sets the current record's "user_id" value
 * @method Operator            setScenarioId()           Sets the current record's "scenario_id" value
 * @method Operator            setUser()                 Sets the current record's "User" value
 * @method Operator            setScenario()             Sets the current record's "Scenario" value
 * @method Operator            setDecisionPoints()       Sets the current record's "DecisionPoints" collection
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOperator extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('operator');
        $this->hasColumn('starting_market_size', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('scenario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Scenario', array(
             'local' => 'scenario_id',
             'foreign' => 'id'));

        $this->hasMany('DecisionPoint as DecisionPoints', array(
             'local' => 'id',
             'foreign' => 'operator_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}