<?php

/**
 * BaseService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $number_of_services
 * @property decimal $setup_fee
 * @property decimal $cost_per_user
 * @property decimal $CAPEX_percentage
 * @property decimal $periodic_fee
 * @property decimal $clients_quota
 * @property integer $tick_to_edit
 * @property integer $technology_id
 * @property integer $operator_id
 * @property Technology $Technology
 * @property Operator $Operator
 * 
 * @method string     getName()               Returns the current record's "name" value
 * @method integer    getNumberOfServices()   Returns the current record's "number_of_services" value
 * @method decimal    getSetupFee()           Returns the current record's "setup_fee" value
 * @method decimal    getCostPerUser()        Returns the current record's "cost_per_user" value
 * @method decimal    getCAPEXPercentage()    Returns the current record's "CAPEX_percentage" value
 * @method decimal    getPeriodicFee()        Returns the current record's "periodic_fee" value
 * @method decimal    getClientsQuota()       Returns the current record's "clients_quota" value
 * @method integer    getTickToEdit()         Returns the current record's "tick_to_edit" value
 * @method integer    getTechnologyId()       Returns the current record's "technology_id" value
 * @method integer    getOperatorId()         Returns the current record's "operator_id" value
 * @method Technology getTechnology()         Returns the current record's "Technology" value
 * @method Operator   getOperator()           Returns the current record's "Operator" value
 * @method Service    setName()               Sets the current record's "name" value
 * @method Service    setNumberOfServices()   Sets the current record's "number_of_services" value
 * @method Service    setSetupFee()           Sets the current record's "setup_fee" value
 * @method Service    setCostPerUser()        Sets the current record's "cost_per_user" value
 * @method Service    setCAPEXPercentage()    Sets the current record's "CAPEX_percentage" value
 * @method Service    setPeriodicFee()        Sets the current record's "periodic_fee" value
 * @method Service    setClientsQuota()       Sets the current record's "clients_quota" value
 * @method Service    setTickToEdit()         Sets the current record's "tick_to_edit" value
 * @method Service    setTechnologyId()       Sets the current record's "technology_id" value
 * @method Service    setOperatorId()         Sets the current record's "operator_id" value
 * @method Service    setTechnology()         Sets the current record's "Technology" value
 * @method Service    setOperator()           Sets the current record's "Operator" value
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('number_of_services', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             'notnull' => true,
             ));
        $this->hasColumn('setup_fee', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('cost_per_user', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('CAPEX_percentage', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('periodic_fee', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('clients_quota', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('tick_to_edit', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('technology_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('operator_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Technology', array(
             'local' => 'technology_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Operator', array(
             'local' => 'operator_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}