<?php

/**
 * BaseArchitecture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $download_bandwidth
 * @property integer $upload_bandwith
 * @property string $image
 * @property integer $technology_id
 * @property Technology $Technology
 * @property Doctrine_Collection $Equipments
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method integer             getDownloadBandwidth()  Returns the current record's "download_bandwidth" value
 * @method integer             getUploadBandwith()     Returns the current record's "upload_bandwith" value
 * @method string              getImage()              Returns the current record's "image" value
 * @method integer             getTechnologyId()       Returns the current record's "technology_id" value
 * @method Technology          getTechnology()         Returns the current record's "Technology" value
 * @method Doctrine_Collection getEquipments()         Returns the current record's "Equipments" collection
 * @method Architecture        setName()               Sets the current record's "name" value
 * @method Architecture        setDownloadBandwidth()  Sets the current record's "download_bandwidth" value
 * @method Architecture        setUploadBandwith()     Sets the current record's "upload_bandwith" value
 * @method Architecture        setImage()              Sets the current record's "image" value
 * @method Architecture        setTechnologyId()       Sets the current record's "technology_id" value
 * @method Architecture        setTechnology()         Sets the current record's "Technology" value
 * @method Architecture        setEquipments()         Sets the current record's "Equipments" collection
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchitecture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('architecture');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('download_bandwidth', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('upload_bandwith', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('technology_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Technology', array(
             'local' => 'technology_id',
             'foreign' => 'id'));

        $this->hasMany('Equipment as Equipments', array(
             'local' => 'id',
             'foreign' => 'architecture_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}