<?php

/**
 * BaseCustomization
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $home_page_content
 * @property string $about_page_content
 * @property string $credits_page_content
 * 
 * @method string        getHomePageContent()      Returns the current record's "home_page_content" value
 * @method string        getAboutPageContent()     Returns the current record's "about_page_content" value
 * @method string        getCreditsPageContent()   Returns the current record's "credits_page_content" value
 * @method Customization setHomePageContent()      Sets the current record's "home_page_content" value
 * @method Customization setAboutPageContent()     Sets the current record's "about_page_content" value
 * @method Customization setCreditsPageContent()   Sets the current record's "credits_page_content" value
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomization extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customization');
        $this->hasColumn('home_page_content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('about_page_content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('credits_page_content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}