<?php

/**
 * BaseArchitecture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $download_bandwidth
 * @property integer $upload_bandwidth
 * @property string $image
 * @property integer $technology_id
 * @property integer $operator_id
 * @property integer $scenario_id
 * @property Technology $Technology
 * @property Operator $Operator
 * @property Scenario $Scenario
 * @property Doctrine_Collection $Equipments
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method integer             getDownloadBandwidth()  Returns the current record's "download_bandwidth" value
 * @method integer             getUploadBandwidth()    Returns the current record's "upload_bandwidth" value
 * @method string              getImage()              Returns the current record's "image" value
 * @method integer             getTechnologyId()       Returns the current record's "technology_id" value
 * @method integer             getOperatorId()         Returns the current record's "operator_id" value
 * @method integer             getScenarioId()         Returns the current record's "scenario_id" value
 * @method Technology          getTechnology()         Returns the current record's "Technology" value
 * @method Operator            getOperator()           Returns the current record's "Operator" value
 * @method Scenario            getScenario()           Returns the current record's "Scenario" value
 * @method Doctrine_Collection getEquipments()         Returns the current record's "Equipments" collection
 * @method Architecture        setName()               Sets the current record's "name" value
 * @method Architecture        setDownloadBandwidth()  Sets the current record's "download_bandwidth" value
 * @method Architecture        setUploadBandwidth()    Sets the current record's "upload_bandwidth" value
 * @method Architecture        setImage()              Sets the current record's "image" value
 * @method Architecture        setTechnologyId()       Sets the current record's "technology_id" value
 * @method Architecture        setOperatorId()         Sets the current record's "operator_id" value
 * @method Architecture        setScenarioId()         Sets the current record's "scenario_id" value
 * @method Architecture        setTechnology()         Sets the current record's "Technology" value
 * @method Architecture        setOperator()           Sets the current record's "Operator" value
 * @method Architecture        setScenario()           Sets the current record's "Scenario" value
 * @method Architecture        setEquipments()         Sets the current record's "Equipments" collection
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchitecture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('architecture');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('download_bandwidth', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('upload_bandwidth', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('technology_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('operator_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('scenario_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Technology', array(
             'local' => 'technology_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Operator', array(
             'local' => 'operator_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Scenario', array(
             'local' => 'scenario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Equipment as Equipments', array(
             'local' => 'id',
             'foreign' => 'architecture_id',
             'orderBy' => 'network_level ASC'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}