<?php

/**
 * AcquiredEquipmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AcquiredEquipmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AcquiredEquipmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AcquiredEquipment');
    }
}