<?php

/**
 * AcquiredEquipment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AcquiredEquipment extends BaseAcquiredEquipment
{
}
