<?php

/**
 * ArchitectureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchitectureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchitectureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Architecture');
    }
}