<?php

/**
 * DecisionPointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DecisionPointTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DecisionPointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DecisionPoint');
    }
}