<?php

/**
 * Equipment
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 */
class Equipment extends BaseEquipment
{
    /**
     * Get the equipment price on a given instant in time (tick)
     *
     * @param integer $tick The instant on time in ticks
     *
     * @return the current price
     */
    public function getPriceByTick($tick = 0)
    {
        $expon = exp(log((1 - $this['NrIni']) / $this['NrIni']) - ((2 * log(9) / $this['deltaT']) * $tick));
        $raise = $this['NrIni'] * (1 + $expon);
        $power = -log($this['valK']) / log(2);

        return round($this['starting_price'] * pow($raise, $power), 2);
    }

    /**
     * Overrided to set the values on some hidden/support fields.
     *
     * @param Doctrine_Connection $conn Optional connection parameter
     *
     * @return void
     */
    public function save(Doctrine_Connection $conn = null)
    {
        if ($this->nature_or_purpose != 'Other') {
            $this->valK = StringHelper::getStringBetween($this->nature_or_purpose, '(', ')');
        }
        if ($this->tecnology_age != 'Other') {
            $this->NrIni = StringHelper::getStringBetween($this->tecnology_age, '(', ')');
        }
        if ($this->setup_speed != 'Other') {
            $this->deltaT = StringHelper::getStringBetween($this->setup_speed, '(', ')');
        }

        $this->scenario_id = $this->Architecture->scenario_id;

        parent::save($conn);
    }
}
