<?php

/**
 * ScenarioTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 */
class ScenarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScenarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Scenario');
    }

   /**
     * Auxiliar method to create a query to fetch Scenarios filtered properly for the current user
     *
     * @param Doctrine_Query $q A Doctrine_Query object
     *
     * @return the built query
     */
    public static function filterByCredential(Doctrine_Query $q)
    {
        $user = sfContext::getInstance()->getUser();

        //if (!$user->hasCredential('admin')) {
        //    $q->andWhere('user_id = ?', $user->getAttribute('id'));
        //}

        return $q;
    }
}
