<?php

/**
 * ScenarioTechnologyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScenarioTechnologyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScenarioTechnologyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScenarioTechnology');
    }
}