<?php

/**
 * Service
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 */
class Service extends BaseService
{
    /**
     * Overrided to set the values on some hidden/support fields.
     *
     * @param Doctrine_Connection $conn Optional connection parameter
     *
     * @return void
     */
    public function save(Doctrine_Connection $conn = null)
    {
        $technology = $this->Technology;
        $this->operator_id = $technology->operator_id;

        parent::save($conn);
    }
}
