<?php

/**
 * TechnologyTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 */
class TechnologyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TechnologyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Technology');
    }

    /**
     * Auxiliar method to create a query to filter Techonology by current chosen scenario only
     *
     * @param Doctrine_Query $q A Doctrine_Query object
     *
     * @return the built query
     */
    public static function filterByScenario(Doctrine_Query $q)
    {
        $user = sfContext::getInstance()->getUser();

        $q->andWhere('scenario_id = ?', $user->getAttribute('scenarioId', 0));

        return $q;
    }
}
