<?php

/**
 * TechnologyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TechnologyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TechnologyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Technology');
    }
}