<?php

/**
 * TickTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TickTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TickTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tick');
    }
}