<?php

/**
 * User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    stimuLearning
 * @subpackage model
 * @author     Artur Melo <adsmelo@ua.pt>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends BaseUser
{

    /**
     * This method will return true if the given passord is correct and false otherwise
     *
     * @param string $password password
     *
     * @return boolean
     */
    public function passwordMatchesPassword($password)
    {
        return $this->getPassword() == $this->getEncryptedPassword($password);
    }

    /**
     * This method will return the user's password encrypted
     *
     * @param string $password password
     *
     * @return string
     */
    public function getEncryptedPassword($password)
    {
        return md5($password);
    }
}
