generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Operator
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          operator
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      
      list:
        fields:
          User:
            credentials: [admin]
        title: ''
        sort: [scenario_id, asc]
        display: [id,starting_market_size,User,Scenario, scenario_id]
        table_method: filterByCredential

      filter:
        display: [user_id,scenario_id]

      form:    ~
      edit:    ~
      new:     ~
