generator:
  class: jRollerDoctrineGenerator #extends sfDoctrineGenerator
  param:
    model_class:           Operator
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          operator
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new: { credentials: [[admin, responsible]] }
        _edit: { credentials: [[admin, responsible]] }
        _delete: { credentials: [[admin, responsible]] }
      fields:
        name: { label: 'Name' }
        starting_market_size: { label: 'Starting market size' }
        user_id: { label: 'User (Controller)' }

      list:
        fields:
          starting_market_size: { renderer: 'number_format', renderer_arguments: [0, ',', '.'] }
          market_share: { label: 'Market Share', renderer: 'FieldRendererHelper::perc' }
          current_market_size: { renderer: 'number_format', renderer_arguments: [0, ',', '.'] }
          net_present_value: { label: 'N.P.V.', renderer: 'FieldRendererHelper::euro'}
          internal_rate_of_return: { label: 'I.R.R.', renderer: 'FieldRendererHelper::perc' }
          payback_period: { label: 'Payback', renderer: 'number_format', renderer_arguments: [2, ',', '.'] }
        max_per_page: 15
        title: 'Operators'
        sort: [scenario_id, asc]
        display: [name, starting_market_size, market_share, current_market_size, net_present_value, internal_rate_of_return, payback_period, User]
        table_method: filterByCredential
        object_actions:
          _show: ~
          _edit:
            credentials: [[admin, responsible]]
            condition:
              variable: Scenario->started
              check: [ false ]
              invert: false
          _delete:
            credentials: [[admin, responsible]]
            condition:
              variable: Scenario->started
              check: [ false ]
              invert: false
        batch_actions: {}

      filter:
        class: false

      form:
        display: [name, starting_market_size, user_id, scenario_id]
        fields:
          user_id: { credentials: [admin] }
          scenario_id: { credentials: [admin] }

      edit:    ~
      new:     ~
      show:
        display:
          Details:
            - name
            - _scenario
            - starting_market_size
            - current_market_size
            - net_present_value
            - internal_rate_of_return
            - payback_period
            - _user
          Simulated Data:
            - _simulated_data_chart
          Market Share Evolution:
            - _market_share_evolution_chart
          Acquired Equipments:
            - _acquired_equipments
        #actions: ~ # check _show_actions.php
