generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Operator
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          operator
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      
      list:
        fields:
          User:
            credentials: [admin]
        max_per_page: 15
        title: ''
        sort: [scenario_id, asc]
        display: [name,starting_market_size,User,Scenario, scenario_id]
        table_method: filterByCredential
        object_actions:
          show:
            action: show
          _edit:
          _delete:
            credentials: [admin]

      filter:
        display: [user_id,scenario_id]

      form:
        display: [name, starting_market_size]
          
      edit:    ~
      new:     ~
