generator:
  class: sfDoctrineGenerator #jRollerDoctrineGenerator
  param:
    model_class:           Operator
    theme:                 admin #jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          operator
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~

      list:
        fields:
          User:
            credentials: [manager]
        max_per_page: 15
        title: ''
        sort: [scenario_id, asc]
        display: [name, starting_market_size, User, Scenario, scenario_id]
        table_method: filterByCredential
        object_actions:
          show: { action: show }
          _edit: { credentials: [manager] }
          _delete:
            credentials: [manager]

      filter:
        display: [user_id,scenario_id]

      form:
        display: [name, starting_market_size, user_id, scenario_id]

      edit:    ~
      new:     ~
      #show:
      #  display:
      #    Operator Simulated Data: [_simulated_data_chart]
      #    Market Share Evolution: [_market_share_evolution_chart]
