generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Scenario
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          scenario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      
      list:
        title: ''
        display: [description,status,total_clients,lifespan,tick_alias,total_decision_points,ticks_between_decision_points]
      
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
