generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Scenario
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          scenario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        edit:
          credentials: [admin]
        delete:
          credentials: [admin]

      fields:  ~
      
      list:
        title: ''
        display: [_description,status,total_clients,lifespan,tick_alias,total_decision_points,ticks_between_decision_points]
        actions:
          _new:
            credentials: [admin]
        object_actions:
          show: ~
          _edit:
            credentials: [admin]
          _delete:
            credentials: [admin]
            
      filter:
        class: false
        
      form:
        display:
          Graph: [_market_share_chart]
          Basic: [description,total_clients,tick_alias,lifespan,total_decision_points,ticks_between_decision_points]
          Market Share Evolution: [starting_level,saturation_level,alpha,beta]
          Financial: [tariffs_erosion_rate,depreciation_rate,interest_rate,elasticity,bankrupcy_limit]
          Quality Vector: [number_of_services_weight,download_weight,upload_weight,rate_weight,fee_weight,occupation_rate_weight,containment_factor_weight,reference_occupation_rate]
      
      edit:
        title: 'Edit Scenario - %%description%%'
        actions:
          _delete:
            credentials: [admin]
          _list:
          _save:
            credentials: [admin]
      
      new: ~
