generator:
  class: sfDoctrineGenerator #jRollerDoctrineGenerator
  param:
    model_class:           Scenario
    theme:                 admin #jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          scenario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        nextStep: { credentials: [manager] }
        nextDecision: { credentials: [manager] }
        finish: { credentials: [manager] }
        edit: { credentials: [manager] }
        delete: { credentials: [manager] }

      fields:
        created_at: { date_format: 'dd/MM/yyyy HH:mm:ss' }
        updated_at: { date_format: 'dd/MM/yyyy HH:mm:ss' }

      list:
        title: 'Scenarios'
        display: [_description,started,total_clients,lifespan,tick_alias,total_decision_points,ticks_between_decision_points,finished]
        fields:
          total_decision_points: { label: '# decision pts'}
          ticks_between_decision_points: { label: 'Ticks between decision pts'}
        actions:
          _new:
            credentials: [manager]
        object_actions: # _list_td_actions.php has been overridden
          show:
            action: show
          _edit:
            credentials: [manager]
          _delete:
            credentials: [manager]
            confirm: 'This removal is irreversible! Are you sure you want to proceed?'

      filter:
        display: [started, tick_alias, finished]

      form:
        display:
          Graph: [_market_penetration_chart]
          Basic: [description,total_clients,tick_alias,lifespan,total_decision_points,ticks_between_decision_points]
          Market Share Evolution: [starting_level,saturation_level,alpha,beta]
          Financial: [tariffs_erosion_rate,depreciation_rate,interest_rate,elasticity,bankrupcy_limit]
          Quality Vector: [number_of_services_weight,download_weight,upload_weight,rate_weight,fee_weight,occupation_rate_weight,containment_factor_weight,reference_occupation_rate]

      edit:
        title: 'Edit Scenario - %%description%%'
        actions:
          _delete:
            credentials: [manager]
          _list:
          _save:
            credentials: [manager]

      new: ~
