generator:
  class: jRollerDoctrineGenerator #extends sfDoctrineGenerator
  param:
    model_class:            Scenario
    theme:                  jroller
    non_verbose_templates:  true
    with_show:              false
    singular:               ~
    plural:                 ~
    route_prefix:           scenario
    with_doctrine_route:    true
    actions_base_class:     sfActions

    config:
      actions:
        startSimulation: { ui-icon: 'play', action: startSimulation, credentials: [[admin, responsible]] }
        nextStep: { ui-icon: 'triangle-1-e', action: advanceSimulation, credentials: [[admin, responsible]] }
        nextDecision: { ui-icon: 'seek-next', action: advanceSimulation, credentials: [[admin, responsible]] }
        finish: { ui-icon: 'seek-end', action: advanceSimulation, credentials: [[admin, responsible]] }

      fields:
        started: { renderer: 'FieldRendererHelper::plainBoolean' }
        finished: { renderer: 'FieldRendererHelper::plainBoolean' }
      # Quality Vector Weights
        number_of_services_weight: { help: 'Small explanation here...' }
        download_weight: { help: 'Small explanation here...' }
        upload_weight: { help: 'Small explanation here...' }
        rate_weight: { help: 'Small explanation here...' }
        fee_weight: { label: 'Fee weight', help: 'Small explanation here...' }
        occupation_rate_weight: { help: 'Small explanation here...' }
        containment_factor_weight: { help: 'Small explanation here...' }
        reference_occupation_rate: { help: 'Small explanation here...' }

      list:
        title: 'Scenarios'
        display: [_description,started,total_clients, current_tick, lifespan,tick_alias,total_decision_points,finished]
        fields:
          total_clients: { renderer: 'number_format', renderer_arguments: [0, ',', '.'] }
          total_decision_points: { label: '# decision pts'}
          ticks_between_decision_points: { label: 'Ticks between decision pts'}
        actions:
          _new: ~
        object_actions: # _list_td_actions.php has been overridden
          _show: ~
          _edit:
            credentials: [[admin, responsible]]
            condition:
              variable: started
              check: [ false ]
              invert: false
          _delete:
            credentials: [[admin, responsible]]
            confirm: 'This removal is irreversible! Are you sure you want to proceed?'
            condition:
              variable: started
              check: [ false ]
              invert: false
        batch_actions: {}

      filter:
        display: [my_role, started, tick_alias, finished]
        fields:
          my_role: { label: 'My role'}

      form:
        display:
          Basic:
            - _market_penetration_chart
            - description
            - total_clients
            - tick_alias
            - lifespan
            - total_decision_points
            - ticks_between_decision_points
            - responsible_id
          Market Share Evolution:
            - starting_level
            - saturation_level
            - alpha
            - beta
          #Graph:
          #  - _market_penetration_chart
          "Geography / Territory":
            - total_area
            - dense_urban_territory
            - dense_urban_area
            - urban_territory
            - urban_area
            - suburban_territory
            - suburban_area
            - rural_territory
            - rural_area
          "Demography / Population":
            - dense_urban_distribution
            - dense_urban_population
            - urban_distribution
            - urban_population
            - suburban_distribution
            - suburban_population
            - rural_distribution
            - rural_population
          Financial:
            - packages_erosion_rate
            - depreciation_rate
            - interest_rate
            - elasticity
            - bankrupcy_limit
          Operators:
            - _operators
          #Quality Vector:
            - number_of_services_weight
            - download_weight
            - upload_weight
            - rate_weight
            - fee_weight
            - occupation_rate_weight
            - containment_factor_weight
            - reference_occupation_rate

      edit:
        title: 'Edit Scenario - %%description%%'
        actions:
          _list: ~
          _save: ~
          _delete: ~

      new: ~
      show:
        #title: 'View Scenario - %%description%%'
        display:
          Basic:
            #- _market_penetration_chart
            - description
            - total_clients
            - tick_alias
            - lifespan
            - total_decision_points
            - ticks_between_decision_points
            - _responsible
          Graph:
            - _market_penetration_chart
          Market Share Evolution:
            - starting_level
            - saturation_level
            - alpha
            - beta
          'Geography / Territory':
            - total_area
            - dense_urban_territory
            - dense_urban_area
            - urban_territory
            - urban_area
            - suburban_territory
            - suburban_area
            - rural_territory
            - rural_area
          'Demography / Population':
            - dense_urban_distribution
            - dense_urban_population
            - urban_distribution
            - urban_population
            - suburban_distribution
            - suburban_population
            - rural_distribution
            - rural_population
          Financial:
            - packages_erosion_rate
            - depreciation_rate
            - interest_rate
            - elasticity
            - bankrupcy_limit
          Operators:
            - _operators
            - number_of_services_weight
            - download_weight
            - upload_weight
            - rate_weight
            - fee_weight
            - occupation_rate_weight
            - containment_factor_weight
            - reference_occupation_rate
#        actions: # check _show_actions.php
#          _list: ~
#          startSimulation: ~
#          _edit: ~
#          _delete: ~
#          nextStep: ~
#          nextDecision: ~
#          finish: ~

