generator:
  class: jRollerDoctrineGenerator #extends sfDoctrineGenerator
  param:
    model_class:            Scenario
    theme:                  jroller
    non_verbose_templates:  true
    with_show:              false
    singular:               ~
    plural:                 ~
    route_prefix:           scenario
    with_doctrine_route:    true
    actions_base_class:     sfActions

    config:
      actions:
        startSimulation: { action: startSimulation, credentials: [manager] }
        nextStep: { action: advanceSimulation, credentials: [manager] }
        nextDecision: { action: advanceSimulation, credentials: [manager] }
        finish: { action: advanceSimulation, credentials: [manager] }

      fields:
        started: { renderer: 'FieldRendererHelper::plainBoolean' }
        finished: { renderer: 'FieldRendererHelper::plainBoolean' }

      list:
        title: 'Scenarios'
        display: [_description,started,total_clients, current_tick, lifespan,tick_alias,total_decision_points,ticks_between_decision_points,finished]
        fields:
          total_clients: { renderer: 'number_format', renderer_arguments: [0, ',', '.'] }
          total_decision_points: { label: '# decision pts'}
          ticks_between_decision_points: { label: 'Ticks between decision pts'}
        actions:
          _new:
            credentials: [manager]
        object_actions: # _list_td_actions.php has been overridden
          _show: ~
          _edit: { credentials: [manager] }
          _delete:
            credentials: [manager]
            confirm: 'This removal is irreversible! Are you sure you want to proceed?'

      filter:
        display: [started, tick_alias, finished]

      form:
        display:
          #Graph:
          #  - _market_penetration_chart
          Basic:
            - _market_penetration_chart
            - description
            - total_clients
            - tick_alias
            - lifespan
            - total_decision_points
            - ticks_between_decision_points
          Market Share Evolution:
            - starting_level
            - saturation_level
            - alpha
            - beta
          Financial:
            - packages_erosion_rate
            - depreciation_rate
            - interest_rate
            - elasticity
            - bankrupcy_limit
          Quality Vector:
            - number_of_services_weight
            - download_weight
            - upload_weight
            - rate_weight
            - fee_weight
            - occupation_rate_weight
            - containment_factor_weight
            - reference_occupation_rate

      edit:
        title: 'Edit Scenario - %%description%%'
        actions:
          _delete:
            credentials: [manager]
          _list:
          _save:
            credentials: [manager]

      new: ~
      show:
        #title: 'View Scenario - %%description%%'
        display:
          Basic:
            #- _market_penetration_chart
            - description
            - total_clients
            - tick_alias
            - lifespan
            - total_decision_points
            - ticks_between_decision_points
          Graph:
            - _market_penetration_chart
          Market Share Evolution:
            - starting_level
            - saturation_level
            - alpha
            - beta
          Financial:
            - packages_erosion_rate
            - depreciation_rate
            - interest_rate
            - elasticity
            - bankrupcy_limit
          Quality Vector:
            - number_of_services_weight
            - download_weight
            - upload_weight
            - rate_weight
            - fee_weight
            - occupation_rate_weight
            - containment_factor_weight
            - reference_occupation_rate
#        actions: # check _show_actions.php
#          _list: ~
#          startSimulation: { credentials: [manager] }
#          _edit: { credentials: [manager] }
#          _delete: { credentials: [manager] }
#          nextStep: { credentials: [manager] }
#          nextDecision: { credentials: [manager] }
#          finish: { credentials: [manager] }

