generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Scenario
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          scenario
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      
      list:
        title: ''
        display: [id,description,status,total_clients,lifespan,tick_alias,total_decision_points,ticks_between_decision_points]
        actions:
          _new:
            credentials: [admin]
            
      filter:
        class: false
        
      form:
        display:
          Basic: [description,total_clients,tick_alias,lifespan,total_decision_points,ticks_between_decision_points]
          Financial: [tariffs_erosion_rate,depreciation_rate,interest_rate,elasticity,bankrupcy_limit]
          Market Share Evolution: [starting_level,saturation_level,alpha,beta]
          Quality Vector: [number_of_services_weight,download_weight,upload_weight,rate_weight,fee_weight,occupation_rate_weight,containment_factor_weight,reference_occupation_rate]
          
      edit:    ~
      new:     ~
