default:
  stylesheets: [scenario.css]

newSuccess:
  javascripts: [flot/jquery.flot.js, flot/jquery.flot.selection.js, marketShareChart.js, calculos.js]
editSuccess:
  javascripts: [flot/jquery.flot.js, flot/jquery.flot.selection.js, marketShareChart.js, calculos.js]
showSuccess:
  javascripts: [flot/jquery.flot.js, flot/jquery.flot.selection.js, marketShareChart.js]
