### START: General user rules ###
login:
  url: /login
  param: { module: default, action: login }

logout:
  url: /logout
  param: { module: default, action: logout }

about:
  url: /about
  param: { module: default, action: about }
### END: General user rules ###

scenario:
  class: sfDoctrineRouteCollection
  options:
    model:                Scenario
    module:               scenario
    prefix_path:          /scenario
    column:               id
    with_wildcard_routes: true

architecture:
  class: sfDoctrineRouteCollection
  options:
    model:                Architecture
    module:               architecture
    prefix_path:          /architecture
    column:               id
    with_wildcard_routes: true

technology:
  class: sfDoctrineRouteCollection
  options:
    model:                Technology
    module:               technology
    prefix_path:          /technology
    column:               id
    with_wildcard_routes: true

equipment:
  class: sfDoctrineRouteCollection
  options:
    model:                Equipment
    module:               equipment
    prefix_path:          /equipment
    column:               id
    with_wildcard_routes: true

operator:
  class: sfDoctrineRouteCollection
  options:
    model:                Operator
    module:               operator
    prefix_path:          /operator
    column:               id
    with_wildcard_routes: true

service:
  class: sfDoctrineRouteCollection
  options:
    model:                Service
    module:               service
    prefix_path:          /service
    column:               id
    with_wildcard_routes: true

user:
  class: sfDoctrineRouteCollection
  options:
    model:                User
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
