# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        GSBL - StimuLearning
    #description:  symfony project
    keywords:     gsbl, stimulearning, market
    language:     en
    #robots:       index, follow

  stylesheets:
    - lib/reset_fonts_base-min.css
    - main.css
    - admin.css

  javascripts:    [lib/jquery-1.6.2.min.js, /sfAdminThemejRollerPlugin/js/jquery-ui.custom.min.js] #lib/jquery-ui.custom.min.js] #, i18n/jquery.ui.datepicker-pt-BR.js]
  #javascripts:    [lib/jquery-1.9.1.min.js, lib/jquery-ui.1.10.3.min.js]

  has_layout:     true
  layout:         layout
