generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           User
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

  ## This entire module is already secured for 'admin' only!
    config:
      actions: ~
      fields:
        is_manager: { renderer: 'FieldRendererHelper::plainBoolean' }
        is_admin: { renderer: 'FieldRendererHelper::plainBoolean' }
        last_login: { date_format: 'dd/MM/yyyy HH:mm:ss' }

      list:
        title: 'Users'
        display: [ name, username, email, is_manager, is_admin, last_login ]

      filter:
        class: false

      form:    ~
      edit:    ~
      new:     ~

      show:
        display: [ name, username, email, is_manager, is_admin, last_login ]
