generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           User
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

  ## This entire module is already secured for 'admin' only!
    config:
      actions: ~
      fields:
        name: { label: 'Name' }
        username: { label: 'Username' }
        email: { label: 'Email' }
        filiation: { label: 'Filiation (University)' }
        department: { label: 'Department / Faculty / School'}
        is_admin: { renderer: 'FieldRendererHelper::plainBoolean' }
        last_login: { date_format: 'dd/MM/yyyy HH:mm:ss' }
        deleted: { renderer: 'FieldRendererHelper::plainBoolean' }

      list:
        title: 'Users'
        display: [ name, username, email, filiation, is_admin, last_login ]
        batch_actions: {}

      filter:
        display: [is_admin, deleted ]

      form:
        display: [ name, username, email, filiation, department, is_admin, new_password, confirm_new_password ]
      edit:
        actions:
          _list: { credentials: [admin] }
          _save: ~
          _save_and_add: { credentials: [admin] }
      new:
        title: 'Register new user'
        fields:
          new_password: { label: Password }
          confirm_new_password: { label: Confirm password }
        actions:
          _list: { credentials: [admin] }
          _save: ~
          _save_and_add: { credentials: [admin] }

      show:
        display: [ name, username, email, filiation, department, is_admin, last_login ]
