generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           Equipment
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          equipment
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        starting_price: { renderer: 'FieldRendererHelper::euro' }

      list:
        title: 'Equipments'
        display: [ name, starting_price, number_of_ports, network_level, life_expectation, equipment_type, nature_or_purpose, tecnology_age, setup_speed ]
        fields:
          number_of_ports: { label: '# of ports'}
          network_level: { label: 'Net. lvl' }
          life_expectation: { label: 'Lifespan', renderer: 'FieldRendererHelper::append', renderer_arguments: ['ticks'] }
          equipment_type: { label: Type }
        actions:
          _new: ~
        object_actions:
          _show: ~
          _edit: ~
          _delete:
            confirm: 'This removal is irreversible! Are you sure you want to proceed?'
        batch_actions:
          _delete: ~

      filter:
        display: [ architecture_id, equipment_type, nature_or_purpose, tecnology_age, setup_speed ]

      form:
        display: [ architecture_id, name, starting_price, number_of_ports, network_level, life_expectation, equipment_type, nature_or_purpose, tecnology_age, setup_speed ]
      edit:    ~
      new:     ~

      show:
        display: [ name, starting_price, number_of_ports, network_level, life_expectation, equipment_type, nature_or_purpose, tecnology_age, setup_speed ]
