generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           Technology
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          technology
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        scenarios_list: { label: Available for scenarios, help: Press "Ctrl" to select multiple items }
        created_at: { label: 'Created At', date_format: 'dd/MM/yyyy HH:mm:ss' }
        updated_at: { label: 'Updated At', date_format: 'dd/MM/yyyy HH:mm:ss' }

      list:
        title: ''
        object_actions:
          show: { action: show }
          _edit: { credentials: [admin] }
          _delete: { credentials: [admin] }

      filter:
        class: false

      form:    ~
      edit:    ~
      new:     ~
