generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Technology
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          technology
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        scenarios_list: { label: Available for scenarios, help: Press "Ctrl" to select multiple items }
      
      list:
        title: ''
      
      filter:
        class: false
      
      form:    ~
      edit:    ~
      new:     ~
