generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           Technology
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          technology
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _edit: { credentials: [[admin, responsible]] }
        _delete: { credentials: [[admin, responsible]] }
      fields:
        scenarios_list: { label: Available for scenarios, help: Press "Ctrl" to select multiple items }
        created_at: { date_format: 'dd/MM/yyyy HH:mm:ss' }
        updated_at: { date_format: 'dd/MM/yyyy HH:mm:ss' }

      list:
        title: 'Technologies'
        display: [ name, description, first_tick_available, decline_A, decline_B, Architecture ]
        table_method: filterByScenario
        actions:
          _new: ~
        object_actions:
          _show: ~
          _edit:
            credentials: [[admin, responsible]]
            condition:
              variable: Scenario->finished
              check: [ false ]
              invert: false
          _delete:
            credentials: [[admin, responsible]]
            confirm: 'This removal is irreversible! Are you sure you want to proceed?'
            condition:
              variable: Scenario->finished
              check: [ false ]
              invert: false
        batch_actions: {}

      filter:
        class: false

      form:    ~
      edit:
        display: [ name, description, decline_A, decline_B, scenario_id ]
      new:
        display: [ name, description, decline_A, decline_B, scenario_id ]

      show:
        display: [ name, description, first_tick_available, decline_A, decline_B, _scenario ]
        #actions: ~ # check _show_actions.php
