generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Architecture
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          architecture
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: ''
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
