generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           Architecture
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          architecture
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
        #_new: { credentials: [[admin, responsible]] }
        #_edit: { credentials: [[admin, responsible]] }
        #_delete: { credentials: [[admin, responsible]] }
      fields:
        name: { label: 'Name' }
        download_bandwidth: { label: 'Download bandwidth' }
        upload_bandwidth: { label: 'Upload bandwidth' }
        technology_id: { label: 'Technology' }

      list:
        title: 'Architectures'
        display: [ name, download_bandwidth, upload_bandwidth, Operator, Technology ]
        table_method: filterByScenario
        fields: # because 'renderer' only works on list
          download_bandwidth: { renderer: 'FieldRendererHelper::append', renderer_arguments: ['Mbps'] }
          upload_bandwidth: { renderer: 'FieldRendererHelper::append', renderer_arguments: ['Mbps'] }
        object_actions:
          _show: ~
          _edit:
            #credentials: [[admin, responsible]]
            condition:
              variable: Scenario->finished
              check: [ false ]
              invert: false
          _delete:
            #credentials: [[admin, responsible]]
            condition:
              variable: Scenario->finished
              check: [ false ]
              invert: false
            confirm: 'This removal is irreversible! Are you sure you want to proceed?'
        batch_actions: {}

      filter:
        class: false

      form:    ~
      edit:    ~
      new:     ~

      show:
        display: [ name, download_bandwidth, upload_bandwidth, image, _operator, _technology ]
        #actions: ~ # check _show_actions.php
