generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           Architecture
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          architecture
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: 'Name' }
        download_bandwidth: { label: 'Download Bandwidth' }
        upload_bandwidth: { label: 'Upload Bandwidth' }
        image: { label: 'Image' }
        technology_id: { label: 'Technology' }
        created_at: { label: 'Created At', date_format: 'dd/MM/yyyy HH:mm:ss' }
        updated_at: { label: 'Updated At', date_format: 'dd/MM/yyyy HH:mm:ss' }

      list:
        title: ''
        display: [ name, download_bandwidth, upload_bandwidth, image, technology_id, created_at ]
        object_actions:
          show: { action: show }
          _edit: { credentials: [admin] }
          _delete: { credentials: [admin] }

      filter:
        class: false

      form:    ~
      edit:    ~
      new:     ~
      show:
        display: [ name, download_bandwidth, upload_bandwidth, image, technology_id, created_at, updated_at ]
