generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           Architecture
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          architecture
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        technology_id: { label: 'Technology' }

      list:
        title: 'Architectures'
        display: [ name, download_bandwidth, upload_bandwidth, Technology ]
        fields: # because 'renderer' only works on list
          download_bandwidth: { renderer: 'FieldRendererHelper::append', renderer_arguments: ['Mbps'] }
          upload_bandwidth: { renderer: 'FieldRendererHelper::append', renderer_arguments: ['Kbps'] }
        actions:
          _new: ~
        object_actions:
          _show: ~
          _edit: ~
          _delete:
            confirm: 'This removal is irreversible! Are you sure you want to proceed?'
        batch_actions:
          _delete: ~

      filter:
        class: false
        #display: [ name, technology_id ]

      form:    ~
      edit:    ~
      new:     ~

      show:
        display: [ name, download_bandwidth, upload_bandwidth, image, technology_id ]
