generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           Architecture
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          architecture
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        technology_id: { label: 'Technology' }
        created_at: { date_format: 'dd/MM/yyyy HH:mm:ss' }
        updated_at: { date_format: 'dd/MM/yyyy HH:mm:ss' }

      list:
        title: 'Architectures'
        display: [ name, download_bandwidth, upload_bandwidth, Technology, created_at ]
        actions:
          _new:
            credentials: [manager]
        object_actions:
          _show: ~
          _edit: { credentials: [manager] }
          _delete:
            credentials: [manager]
            confirm: 'This removal is irreversible! Are you sure you want to proceed?'
        batch_actions:
          _delete: { credentials: [manager] }

      filter:
        class: false

      form:    ~
      edit:    ~
      new:     ~

      show:
        display: [ name, download_bandwidth, upload_bandwidth, image, technology_id, created_at, updated_at ]
