all:
  has_layout:     true

loginSuccess:
  has_layout:     true
  stylesheets:    [-*, reset.css, main.css]
  javascripts:    [-*, lib/jquery_1.5.1.js, flot/jquery.flot.js, marketShareChart.js]

error404Success:
  layout: 404
