Equipment:
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(150), notnull: true }
    starting_price: { type: decimal, notnull: true } #Preço inicial
    number_of_ports: { type: integer, notnull: true } #Capacidade
    network_level: { type: integer, notnull: true } #Nível na rede
    life_expectation: { type: integer, notnull: true } #Esperança de vida
    equipment_type: { type: enum, values: [~,Wired,Wireless], notnull: true }
    nature_or_purpose:
      type: enum
      values:
        - ~
        - Construção civil (1)
        - Cabos de cobre (1)
        - Cabos de fibra (0.8)
        - Electrónica (0.9)
        - Componentes ópticos avançados (0.7)
        - Componentes ópticos passivos (0.8)
    tecnology_age:
      type: enum
      values:
        - ~
        - Velha (0.5)
        - Madura (0.1)
        - Nova (0.01)
        - Emergente (0.001)
    setup_speed:
      type: enum
      values:
        - ~
        - Muito rápida (5)
        - Rápida (10)
        - Lenta (20)
        - Muito lenta (40)
    architecture_id: { type: integer, notnull: true }
  relations:
    Architecture:
      foreignAlias: Equipments

AcquiredEquipment:
  options:
    symfony:
      form: false
      filter: false
  columns:
    quantity: { type: integer, notnull: true }
    price: { type: decimal, notnull: true }
    is_obsolete: { type: boolean, default: false }
    tick_id: { type: integer, notnull: true }
    equipment_id: { type: integer, notnull: true }
  relations:
    Tick:
      foreignAlias: AcquiredEquipments
    Equipment: 
