Architecture:
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(100), notnull: true }
    download_bandwidth: { type: integer, notnull: true }
    upload_bandwidth: { type: integer, notnull: true }
    image: { type: string(255) }
    technology_id: { type: integer, notnull: true }
  relations:
    Technology:
      foreignAlias: Architecture
      type: one
      foreignType: one
