Technology:
  options:
    symfony:
      filter: false
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(100), notnull: true }
    description: { type: string(500) }
    first_tick_available: { type: integer, default: 0, notnull: true }
    decline_A: { type: float, notnull: true }
    decline_B: { type: float, notnull: true }
  relations:
    #Scenarios: # Defined on Scenario schema
