Service:
  options:
    symfony:
      filter: false
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(100), notnull: true }
    setup_fee: { type: decimal, notnull: true }
    cost_per_user: { type: decimal, notnull: true }
    CAPEX_percentage: { type: float, notnull: true }
    tick_to_apply: { type: integer, notnull: true }
  ## For the relations ##
    operator_id: { type: integer, notnull: true }
    technology_id: { type: integer, notnull: true }
  relations:
    Operator:
      foreignAlias: Services
    Technology:
      foreignAlias: Services
