Technology:
  options:
    symfony:
      filter: false
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(100), notnull: true }
    description: { type: string(500) }
    first_tick_available: { type: integer, default: 0, notnull: true }
    decline_A: { type: decimal, scale: 3, notnull: true }
    decline_B: { type: decimal, scale: 3, notnull: true }
  ## For the relations ##
    scenario_id: { type: integer, notnull: true }
  relations:
    Scenario:
      foreignAlias: Technologies
      onDelete: CASCADE

LibTech:
  options:
    symfony:
      filter: false
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(100), notnull: true }
    description: { type: string(500) }
    decline_A: { type: decimal, scale: 3, notnull: true }
    decline_B: { type: decimal, scale: 3, notnull: true }
