Tariff:
  options:
    symfony:
      filter: false
  actAs:
    Timestampable: ~
  columns:
    tick: { type: integer, notnull: true }
    
    operator_id: { type: integer, notnull: true }
    #scenario_id: { type: integer, notnull: true }
  relations:
    Operator:
      foreignAlias: DecisionPoints
    #Scenario:
    #  foreignAlias: DecisionPoints
