Service:
  options:
    symfony:
      filter: false
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(100), notnull: true }
    number_of_services: { type: integer, default: 1, notnull: true }
    setup_fee: { type: decimal, notnull: true }
    cost_per_user: { type: decimal, notnull: true }
    CAPEX_percentage: { type: decimal, notnull: true }
    monthly_fee: { type: decimal, notnull: true }
    periodic_fee: { type: decimal } #hidden
    clients_quota: { type: decimal, notnull: true }
    tick_to_edit: { type: integer, default: 0, notnull: true } #hidden
  ## For the relations ##
    technology_id: { type: integer, notnull: true }
    operator_id: { type: integer } #hidden
  relations:
    Technology:
      foreignAlias: Services
      onDelete: CASCADE
    Operator:
      foreignAlias: Services
      onDelete: CASCADE
