Architecture:
  options:
    symfony:
      filter: false
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(100), notnull: true }
    download_bandwidth: { type: integer, notnull: true }
    upload_bandwidth: { type: integer, notnull: true }
    image: { type: string(255) }
    operator_id: { type: integer, notnull: true }
    technology_id: { type: integer, notnull: true }
    scenario_id: { type: integer } # hidden
  relations:
    Operator:
      foreignAlias: Architectures
      onDelete: CASCADE
    Technology:
      foreignAlias: Architectures
      onDelete: CASCADE
    Scenario:
      foreignAlias: Architectures
      onDelete: CASCADE
    Equipments:
      type: many
      class: Equipment
      orderBy: network_level ASC
      local: id
      foreign: architecture_id

LibArch:
  options:
    symfony:
      filter: false
  actAs:
    Timestampable: ~
  columns:
    name: { type: string(100), notnull: true }
    download_bandwidth: { type: integer, notnull: true }
    upload_bandwidth: { type: integer, notnull: true }
    image: { type: string(255) }
    tech_id: { type: integer, notnull: true }
  relations:
    Technology:
      class: LibTech
      foreignAlias: Architecture
      type: one
      foreignType: one
      local: tech_id
      foreign: id
      onDelete: CASCADE
