Customization:
  options:
    symfony:
      filter: false
  columns:
    home_page_content:
      type: string
      notnull: true
    about_page_content:
      type: string
      notnull: true
    credits_page_content:
      type: string
      notnull: true
    jquery_ui_theme:
      type: enum
      default: redmond
      values:
        - black-tie
        - blitzer
        - cupertino
        - dark-hive
        - dot-luv
        - eggplant
        - excite-bike
        - flick
        - hot-sneaks
        - humanity
        - le-frog
        - mint-choc
        - overcast
        - pepper-grinder
        - redmond
        - smoothness
        - south-street
        - start
        - sunny
        - swanky-purse
        - trontastic
        - ui-darkness
        - ui-lightness
        - vader

MigrationVersion:
  options:
    symfony:
      form: false
      filter: false
  columns:
    version:
      type: integer
      default: 0
