generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           Service
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          service
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        setup_fee: { renderer: 'FieldRendererHelper::euro' }
        cost_per_user: { renderer: 'FieldRendererHelper::euro' }
        created_at: { date_format: 'dd/MM/yyyy HH:mm:ss' }
        updated_at: { date_format: 'dd/MM/yyyy HH:mm:ss' }

      list:
        title: 'Services'
        display: [ name, setup_fee, cost_per_user, CAPEX_percentage, tick_to_apply ]

      filter:
        class: false

      form:    ~
      edit:    ~
      new:     ~

      show:
        display: [ name, setup_fee, cost_per_user, CAPEX_percentage, tick_to_apply, created_at, updated_at ]
