generator:
  class: jRollerDoctrineGenerator
  param:
    model_class:           Service
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          service
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: 'Name' }
        number_of_services: { label: 'Number of services' }
        setup_fee: { label: 'Setup fee', renderer: 'FieldRendererHelper::euro' }
        cost_per_user: { label: 'Cost per user', renderer: 'FieldRendererHelper::euro' }
        CAPEX_percentage: { label: 'CAPEX percentage', renderer: 'FieldRendererHelper::perc' }
        monthly_fee: { label: 'Monthly fee' }
        periodic_fee: { label: 'Periodic fee' }
        clients_quota: { label: 'Clients quota' }
        technology_id: { label: 'Technology' }

      list:
        title: 'Services'
        display: [ name, setup_fee, cost_per_user, CAPEX_percentage, monthly_fee, Technology, Operator ]
        table_method: filterByCredential
        batch_actions: {}

      filter:
        class: false

      form:    ~
      edit:    ~
      new:     ~

      show:
        display: [ name, setup_fee, cost_per_user, CAPEX_percentage, monthly_fee, _technology, _operator ]
